#!/usr/bin/env bash

export CONTECO_LABEL="kafka_rest.tocloud - ContEco"
export CONTECO_DESCRIPTION="Confluent Kafka REST to cloud image, with configuration changes."

export CONTECO_TYPE="kafka_rest"
export CONTECO_NAME="tocloud"
export CONTECO_TAG="5.4.0"

export CONTECO_BASE="external.kafka_rest:5.4.0"
export CONTECO_BUILD="image-base"
