#!/usr/bin/env bash

export CONTECO_LABEL="kafka_rest.sasl - ContEco"
export CONTECO_DESCRIPTION="Confluent Kafka REST image, with SASL authentication."

export CONTECO_TYPE="kafka_rest"
export CONTECO_NAME="sasl"
export CONTECO_TAG="6.0.0"

export CONTECO_BASE="external.kafka_rest:6.0.0"
export CONTECO_BUILD="image-base"
